// Generated by seite: when an OpenCode session goes idle, run `seite check`
// and, if the site has errors, send them back so the agent fixes them.
// Delete this file to opt out (`seite upgrade` won't recreate it).
export const SeiteCheck = async ({ client, $, directory }) => {
  const continued = new Set();
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return;
      const sessionID = event.properties?.sessionID;
      if (!sessionID) return;
      const input = JSON.stringify({
        hook_event_name: "session.idle",
        session_id: sessionID,
        cwd: directory,
        stop_hook_active: continued.has(sessionID),
      });
      continued.delete(sessionID);
      let message;
      try {
        const out = await $`seite check --hook opencode < ${new Response(input)}`
          .cwd(directory)
          .quiet()
          .nothrow()
          .text();
        message = JSON.parse(out || "{}").message;
      } catch {
        return;
      }
      if (!message) return;
      continued.add(sessionID);
      await client.session.prompt({
        path: { id: sessionID },
        body: { parts: [{ type: "text", text: message }] },
      });
    },
  };
};
