//! Turn-end ("stop") hooks that run `seite check` inside coding agents.
//!
//! When an agent finishes its turn in a seite site, the hook runs
//! `seite check --hook <agent>`. If the site has **errors** (warnings never
//! block), the hook hands the compiler-style diagnostics back to the agent in
//! that harness's protocol so it fixes them before stopping. A clean site, a
//! directory without `seite.toml`, and any internal failure all pass silently:
//! a broken hook must never break the agent session.
//!
//! | Agent    | Hook config                          | Event          | Continue the agent with               | Loop guard                 |
//! |----------|--------------------------------------|----------------|---------------------------------------|----------------------------|
//! | claude   | `.claude/settings.json` `hooks.Stop` | `Stop`         | `hookSpecificOutput.additionalContext`| `stop_hook_active`         |
//! | codex    | `.codex/hooks.json` `hooks.Stop`     | `Stop`         | `{"decision":"block","reason":…}`     | `stop_hook_active`         |
//! | cursor   | `.cursor/hooks.json` `hooks.stop`    | `stop`         | `{"followup_message":…}`              | `loop_count`, `status`     |
//! | opencode | `.opencode/plugins/seite-check.js`   | `session.idle` | plugin sends `{"message"}` as prompt  | plugin's `stop_hook_active`|
//!
//! Every protocol here exits 0 and speaks JSON on stdout, so a crash or a
//! non-zero exit is always the harness's "hook failed, carry on" path.
//!
//! `seite init` writes the hooks with the other harness files; `seite upgrade`
//! merges them into existing configs once per agent and records that in
//! `.seite/config.json` (`hooks_installed`), so a hook the user deleted stays
//! deleted.

use std::io::{IsTerminal, Read};
use std::path::{Path, PathBuf};
use std::time::Duration;

use serde_json::{json, Map, Value};

use crate::cli::harness::{Agent, PlannedFile};
use crate::diagnostics::Diagnostics;

/// Seconds each harness waits for the hook before giving up (fail-open).
pub const HOOK_TIMEOUT_SECS: u64 = 120;

/// Most diagnostic lines handed back to the agent in one go.
pub const MAX_LINES: usize = 40;

/// The line that tells the agent what to do with the diagnostics.
pub const INSTRUCTION: &str =
    "Fix these `seite check` errors, then finish. Run `seite check` to confirm.";

/// Marker every seite hook command contains; used to detect an installed hook.
const COMMAND_MARKER: &str = "seite check --hook";

/// How long to wait for the harness to close stdin before checking anyway.
const STDIN_TIMEOUT: Duration = Duration::from_secs(5);

/// OpenCode plugin file (OpenCode has no declarative hook config; project
/// plugins in `.opencode/plugins/` load automatically).
pub const OPENCODE_PLUGIN_PATH: &str = ".opencode/plugins/seite-check.js";

const OPENCODE_PLUGIN: &str = r#"// Generated by seite: when an OpenCode session goes idle, run `seite check`
// and, if the site has errors, send them back so the agent fixes them.
// Delete this file to opt out (`seite upgrade` won't recreate it).
export const SeiteCheck = async ({ client, $, directory }) => {
  const continued = new Set();
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return;
      const sessionID = event.properties?.sessionID;
      if (!sessionID) return;
      const input = JSON.stringify({
        hook_event_name: "session.idle",
        session_id: sessionID,
        cwd: directory,
        stop_hook_active: continued.has(sessionID),
      });
      continued.delete(sessionID);
      let message;
      try {
        const out = await $`seite check --hook opencode < ${new Response(input)}`
          .cwd(directory)
          .quiet()
          .nothrow()
          .text();
        message = JSON.parse(out || "{}").message;
      } catch {
        return;
      }
      if (!message) return;
      continued.add(sessionID);
      await client.session.prompt({
        path: { id: sessionID },
        body: { parts: [{ type: "text", text: message }] },
      });
    },
  };
};
"#;

/// The command each harness runs (bare `seite` on PATH, like the MCP config).
pub fn hook_command(agent: Agent) -> String {
    format!("{COMMAND_MARKER} {}", agent.id())
}

/// The file that holds `agent`'s stop hook, relative to the site root.
pub fn hook_path(agent: Agent) -> &'static str {
    match agent {
        Agent::Claude => ".claude/settings.json",
        Agent::Codex => ".codex/hooks.json",
        Agent::Cursor => ".cursor/hooks.json",
        Agent::Opencode => OPENCODE_PLUGIN_PATH,
    }
}

// ---------------------------------------------------------------------------
// Config generation + merging
// ---------------------------------------------------------------------------

/// Why a hook couldn't be merged into an existing config.
#[derive(Debug, PartialEq, Eq)]
pub struct Unmergeable;

/// Add seite's stop hook to a JSON hook config (`.claude/settings.json`,
/// `.codex/hooks.json`, `.cursor/hooks.json`), keeping every other hook and
/// key in place. `Ok(true)` when added, `Ok(false)` when a seite hook is
/// already there, `Err` when the shape isn't one we can extend safely (e.g.
/// `hooks` isn't an object). Not for OpenCode, whose hook is a plugin file.
pub fn merge_hook(agent: Agent, doc: &mut Map<String, Value>) -> Result<bool, Unmergeable> {
    let (event, entry) = match agent {
        Agent::Claude => (
            "Stop",
            json!({ "hooks": [{
                "type": "command",
                "command": hook_command(agent),
                "timeout": HOOK_TIMEOUT_SECS
            }] }),
        ),
        Agent::Codex => (
            "Stop",
            json!({ "hooks": [{
                "type": "command",
                "command": hook_command(agent),
                "timeout": HOOK_TIMEOUT_SECS,
                "statusMessage": "Running seite check"
            }] }),
        ),
        Agent::Cursor => {
            if !doc.contains_key("version") {
                // Cursor requires the schema version; put it first in a new file.
                let rest = std::mem::take(doc);
                doc.insert("version".into(), json!(1));
                doc.extend(rest);
            }
            (
                "stop",
                json!({ "command": hook_command(agent), "timeout": HOOK_TIMEOUT_SECS }),
            )
        }
        Agent::Opencode => return Err(Unmergeable),
    };
    let hooks = doc
        .entry("hooks")
        .or_insert_with(|| Value::Object(Map::new()))
        .as_object_mut()
        .ok_or(Unmergeable)?;
    let list = hooks
        .entry(event)
        .or_insert_with(|| Value::Array(Vec::new()))
        .as_array_mut()
        .ok_or(Unmergeable)?;
    if list.iter().any(|v| v.to_string().contains(COMMAND_MARKER)) {
        return Ok(false);
    }
    list.push(entry);
    Ok(true)
}

/// Whether `text` (a hook config file) already contains a seite stop hook.
pub fn has_seite_hook(text: &str) -> bool {
    text.contains(COMMAND_MARKER)
}

/// The content of a new hook file for `agent` (for Claude, a settings file
/// holding only the hook; new sites get it merged into the full settings).
pub fn new_hook_file(agent: Agent) -> String {
    if agent == Agent::Opencode {
        return OPENCODE_PLUGIN.to_string();
    }
    let mut doc = Map::new();
    let _ = merge_hook(agent, &mut doc);
    crate::cli::harness::pretty_json(&Value::Object(doc))
}

/// The one-paragraph note for AGENTS.md "Verify Your Change": where each
/// selected agent's hook lives and how to opt out.
pub fn verify_note(agents: &[Agent]) -> String {
    let places: Vec<String> = agents
        .iter()
        .map(|&agent| {
            let extra = match agent {
                Agent::Claude => " (`hooks.Stop`)",
                Agent::Codex => " (approve it once in `/hooks`)",
                _ => "",
            };
            format!("{} `{}`{extra}", agent.label(), hook_path(agent))
        })
        .collect();
    format!(
        "When you finish a turn, a stop hook runs `seite check --hook <agent>` and hands any errors back to you (warnings never block): {}. Everyone working on the site needs seite 0.20 or newer on `PATH` (older versions don't have `seite check` and the hook will fail). Delete the hook to opt out; `seite upgrade` won't re-add it.\n\n",
        places.join(", ")
    )
}

/// Add the stop hooks for `agents` to a fresh-site plan: merge Claude's into
/// the planned `.claude/settings.json`, add the other agents' hook files.
pub fn extend_plan(files: &mut Vec<PlannedFile>, agents: &[Agent]) {
    for &agent in agents {
        let path = hook_path(agent);
        if agent == Agent::Claude {
            let Some(settings) = files.iter_mut().find(|f| f.path == path) else {
                continue;
            };
            if let Ok(Value::Object(mut doc)) = serde_json::from_str(&settings.content) {
                if merge_hook(agent, &mut doc) == Ok(true) {
                    settings.content = crate::cli::harness::pretty_json(&Value::Object(doc));
                }
            }
        } else {
            files.push(PlannedFile {
                path: path.to_string(),
                content: new_hook_file(agent),
            });
        }
    }
}

// ---------------------------------------------------------------------------
// `seite check --hook <agent>`
// ---------------------------------------------------------------------------

/// Run the check as `agent`'s turn-end hook. Never returns an error: every
/// failure path prints a short note on stderr and lets the agent stop.
pub fn run(agent: Agent, include_drafts: bool) -> anyhow::Result<()> {
    // stdout carries only the protocol document; stray output goes to stderr.
    crate::output::json::redirect_stdout_to_stderr();
    let input = read_stdin_json();
    let outcome = std::panic::catch_unwind(|| evaluate(agent, &input, include_drafts));
    match outcome {
        Ok(Ok(Some(doc))) => crate::output::json::emit_document(&doc),
        Ok(Ok(None)) => {
            // Cursor expects JSON on stdout for every run.
            if agent == Agent::Cursor {
                crate::output::json::emit_document(&json!({}));
            }
        }
        Ok(Err(e)) => eprintln!("seite check --hook: skipped ({e:#})"),
        Err(_) => eprintln!("seite check --hook: skipped (internal error)"),
    }
    Ok(())
}

/// Decide what the hook prints: `Some(json)` to keep the agent going, `None`
/// to let it stop.
fn evaluate(agent: Agent, input: &Value, include_drafts: bool) -> anyhow::Result<Option<Value>> {
    let Some(root) = find_site_root(&start_dirs(input)) else {
        return Ok(None);
    };
    if should_skip(agent, input, &root) {
        return Ok(None);
    }
    let diagnostics = crate::cli::check::check_site(&root, include_drafts)?;
    Ok(block_reason(&diagnostics).map(|reason| encode(agent, input, &reason)))
}

/// Directories to look for the site in, most specific first: the project
/// directory the harness reports, then the session's `cwd`, then ours.
fn start_dirs(input: &Value) -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    for var in ["CLAUDE_PROJECT_DIR", "CURSOR_PROJECT_DIR"] {
        if let Some(dir) = std::env::var_os(var).filter(|v| !v.is_empty()) {
            dirs.push(PathBuf::from(dir));
        }
    }
    if let Some(cwd) = input.get("cwd").and_then(Value::as_str) {
        dirs.push(PathBuf::from(cwd));
    }
    if let Ok(cwd) = std::env::current_dir() {
        dirs.push(cwd);
    }
    dirs
}

/// The nearest directory (a start dir or one of its ancestors) holding a
/// `seite.toml`.
pub fn find_site_root(starts: &[PathBuf]) -> Option<PathBuf> {
    starts.iter().find_map(|start| {
        start
            .ancestors()
            .find(|dir| dir.join("seite.toml").is_file())
            .map(Path::to_path_buf)
    })
}

/// Loop guards: never block a turn the hook already continued, or one that
/// didn't complete normally.
pub fn should_skip(agent: Agent, input: &Value, root: &Path) -> bool {
    if input.get("stop_hook_active").and_then(Value::as_bool) == Some(true) {
        return true;
    }
    // Cursor runs its own `stop` hooks and also imports Claude Code's (from
    // `.claude/settings.json`), with Cursor's input either way.
    let in_cursor = agent == Agent::Cursor || runs_in_cursor(input);
    if in_cursor {
        if agent != Agent::Cursor && cursor_hook_installed(root) {
            return true; // the native Cursor hook reports instead
        }
        if input
            .get("status")
            .and_then(Value::as_str)
            .is_some_and(|s| s != "completed")
        {
            return true;
        }
        if input.get("loop_count").and_then(Value::as_u64).unwrap_or(0) >= 1 {
            return true;
        }
    }
    false
}

fn cursor_hook_installed(root: &Path) -> bool {
    std::fs::read_to_string(root.join(hook_path(Agent::Cursor)))
        .is_ok_and(|text| has_seite_hook(&text))
}

/// The message handed to the agent, or `None` when there are no errors.
/// Warnings are left out: they never block.
pub fn block_reason(diagnostics: &Diagnostics) -> Option<String> {
    let errors: Vec<_> = diagnostics.iter().filter(|d| d.is_error()).collect();
    if errors.is_empty() {
        return None;
    }
    let mut lines = Vec::new();
    let mut shown = 0;
    for d in &errors {
        let rendered = d.to_string();
        let count = rendered.lines().count();
        if lines.len() + count > MAX_LINES {
            break;
        }
        lines.extend(rendered.lines().map(str::to_string));
        shown += 1;
    }
    let total = errors.len();
    let mut msg = format!(
        "seite check found {total} error{}:\n",
        if total == 1 { "" } else { "s" }
    );
    for line in &lines {
        msg.push_str(line);
        msg.push('\n');
    }
    if shown < total {
        msg.push_str(&format!(
            "... and {} more (run `seite check` to see all)\n",
            total - shown
        ));
    }
    msg.push_str(INSTRUCTION);
    Some(msg)
}

/// Wrap `reason` in the protocol of the harness that ran the hook.
pub fn encode(agent: Agent, input: &Value, reason: &str) -> Value {
    match agent {
        // Claude Code: `additionalContext` continues the turn like
        // `decision: "block"` (same loop protections) but is shown as "Stop
        // hook feedback" instead of a hook error. When Cursor runs Claude's
        // hooks it only maps `decision: "block"` to a follow-up.
        Agent::Claude if !runs_in_cursor(input) => json!({
            "hookSpecificOutput": { "hookEventName": "Stop", "additionalContext": reason }
        }),
        Agent::Claude | Agent::Codex => json!({ "decision": "block", "reason": reason }),
        Agent::Cursor => json!({ "followup_message": reason }),
        Agent::Opencode => json!({ "message": reason }),
    }
}

/// Whether Cursor ran the hook (its input carries `cursor_version`).
fn runs_in_cursor(input: &Value) -> bool {
    input.get("cursor_version").is_some()
}

/// The hook input JSON from stdin (`{}` when there is none: a terminal, an
/// empty pipe, invalid JSON, or a harness that never closes stdin).
fn read_stdin_json() -> Value {
    if std::io::stdin().is_terminal() {
        return json!({});
    }
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let mut buf = String::new();
        let _ = std::io::stdin().read_to_string(&mut buf);
        let _ = tx.send(buf);
    });
    rx.recv_timeout(STDIN_TIMEOUT)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .filter(Value::is_object)
        .unwrap_or_else(|| json!({}))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diagnostics::Diagnostic;

    fn errors(n: usize) -> Diagnostics {
        let mut d = Diagnostics::new();
        for i in 0..n {
            d.push(
                Diagnostic::error("frontmatter-parse", format!("bad {i}"))
                    .with_file(format!("content/posts/{i:02}.md"))
                    .with_line(2)
                    .with_column(1),
            );
        }
        d
    }

    #[test]
    fn block_reason_only_for_errors() {
        assert!(block_reason(&Diagnostics::new()).is_none());
        let warn: Diagnostics = Diagnostic::warning("broken-link", "x").into();
        assert!(block_reason(&warn).is_none());

        let mut d = errors(1);
        d.push(Diagnostic::warning("broken-link", "not shown"));
        let msg = block_reason(&d).unwrap();
        assert!(msg.starts_with("seite check found 1 error:\n"), "{msg}");
        assert!(msg.contains("content/posts/00.md:2:1: error[frontmatter-parse]: bad 0"));
        assert!(!msg.contains("not shown"));
        assert!(msg.ends_with(INSTRUCTION));
    }

    #[test]
    fn block_reason_caps_lines() {
        let msg = block_reason(&errors(55)).unwrap();
        assert!(msg.starts_with("seite check found 55 errors:\n"));
        let shown = msg.lines().filter(|l| l.contains("error[")).count();
        assert_eq!(shown, MAX_LINES);
        assert!(msg.contains("... and 15 more"), "{msg}");

        // Hints take a second line; the cap counts lines, not diagnostics.
        let mut hinted = Diagnostics::new();
        for i in 0..30 {
            hinted.push(Diagnostic::error("x", format!("m{i}")).with_hint("fix it"));
        }
        let msg = block_reason(&hinted).unwrap();
        assert_eq!(msg.lines().filter(|l| l.contains("hint:")).count(), 20);
        assert!(msg.contains("... and 10 more"));
    }

    #[test]
    fn encode_per_protocol() {
        let plain = json!({ "stop_hook_active": false });
        assert_eq!(
            encode(Agent::Claude, &plain, "r"),
            json!({ "hookSpecificOutput": { "hookEventName": "Stop", "additionalContext": "r" } })
        );
        let block = json!({ "decision": "block", "reason": "r" });
        assert_eq!(encode(Agent::Codex, &plain, "r"), block);
        // Claude's hook imported by Cursor: the shape Cursor maps to a follow-up.
        let cursor_input = json!({ "cursor_version": "2.0" });
        assert_eq!(encode(Agent::Claude, &cursor_input, "r"), block);
        assert_eq!(
            encode(Agent::Cursor, &cursor_input, "r"),
            json!({ "followup_message": "r" })
        );
        assert_eq!(
            encode(Agent::Opencode, &plain, "r"),
            json!({ "message": "r" })
        );
    }

    #[test]
    fn loop_guards() {
        let tmp = tempfile::TempDir::new().unwrap();
        let root = tmp.path();
        let active = json!({ "stop_hook_active": true });
        let fresh = json!({ "stop_hook_active": false });
        for agent in [Agent::Claude, Agent::Codex, Agent::Opencode] {
            assert!(should_skip(agent, &active, root));
            assert!(!should_skip(agent, &fresh, root));
        }
        // Cursor: one follow-up per conversation, only after a completed turn.
        let cursor = |v: Value| should_skip(Agent::Cursor, &v, root);
        assert!(!cursor(json!({ "status": "completed", "loop_count": 0 })));
        assert!(cursor(json!({ "status": "completed", "loop_count": 1 })));
        assert!(cursor(json!({ "status": "aborted", "loop_count": 0 })));
        assert!(!cursor(json!({})));

        // Claude's hook imported by Cursor defers to the native Cursor hook.
        let in_cursor = json!({ "cursor_version": "2.0", "status": "completed", "loop_count": 0 });
        assert!(!should_skip(Agent::Claude, &in_cursor, root));
        let guarded = json!({ "cursor_version": "2.0", "loop_count": 1 });
        assert!(should_skip(Agent::Claude, &guarded, root));
        std::fs::create_dir_all(root.join(".cursor")).unwrap();
        std::fs::write(
            root.join(".cursor/hooks.json"),
            new_hook_file(Agent::Cursor),
        )
        .unwrap();
        assert!(should_skip(Agent::Claude, &in_cursor, root));
        assert!(!should_skip(
            Agent::Cursor,
            &json!({ "loop_count": 0 }),
            root
        ));
    }

    #[test]
    fn merge_hook_is_additive_and_idempotent() {
        let mut doc: Map<String, Value> = serde_json::from_value(json!({
            "permissions": { "allow": ["Read"] },
            "hooks": {
                "Stop": [{ "hooks": [{ "type": "command", "command": "other" }] }],
                "PreToolUse": [{ "matcher": "Bash", "hooks": [] }]
            }
        }))
        .unwrap();
        assert_eq!(merge_hook(Agent::Claude, &mut doc), Ok(true));
        assert_eq!(merge_hook(Agent::Claude, &mut doc), Ok(false));
        let stop = doc["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 2);
        assert_eq!(stop[0]["hooks"][0]["command"], "other");
        assert_eq!(stop[1]["hooks"][0]["command"], "seite check --hook claude");
        assert!(doc["hooks"].get("PreToolUse").is_some());
        // Key order is kept: permissions stays first.
        assert_eq!(doc.keys().next().unwrap(), "permissions");

        let mut bad: Map<String, Value> =
            serde_json::from_value(json!({ "hooks": "nope" })).unwrap();
        assert_eq!(merge_hook(Agent::Codex, &mut bad), Err(Unmergeable));
        let mut bad: Map<String, Value> =
            serde_json::from_value(json!({ "hooks": { "stop": {} } })).unwrap();
        assert_eq!(merge_hook(Agent::Cursor, &mut bad), Err(Unmergeable));
    }

    #[test]
    fn new_hook_files_have_documented_shapes() {
        let cursor: Value = serde_json::from_str(&new_hook_file(Agent::Cursor)).unwrap();
        assert_eq!(cursor["version"], 1);
        assert_eq!(
            cursor["hooks"]["stop"][0]["command"],
            "seite check --hook cursor"
        );
        let text = new_hook_file(Agent::Cursor);
        assert!(text.find("\"version\"").unwrap() < text.find("\"hooks\"").unwrap());

        // An existing Cursor file without a version gets one, first.
        let mut doc: Map<String, Value> =
            serde_json::from_value(json!({ "hooks": { "afterFileEdit": [] } })).unwrap();
        assert_eq!(merge_hook(Agent::Cursor, &mut doc), Ok(true));
        assert_eq!(doc.keys().next().unwrap(), "version");

        let codex: Value = serde_json::from_str(&new_hook_file(Agent::Codex)).unwrap();
        let handler = &codex["hooks"]["Stop"][0]["hooks"][0];
        assert_eq!(handler["type"], "command");
        assert_eq!(handler["command"], "seite check --hook codex");
        assert_eq!(handler["timeout"], HOOK_TIMEOUT_SECS);

        let plugin = new_hook_file(Agent::Opencode);
        assert!(plugin.contains("session.idle"));
        assert!(plugin.contains("seite check --hook opencode"));
        assert!(has_seite_hook(&plugin));
    }

    #[test]
    fn extend_plan_merges_claude_settings_and_adds_files() {
        let mut files = vec![PlannedFile {
            path: ".claude/settings.json".into(),
            content: crate::cli::harness::pretty_json(&json!({ "permissions": {} })),
        }];
        extend_plan(&mut files, &Agent::ALL);
        let settings: Value = serde_json::from_str(&files[0].content).unwrap();
        assert_eq!(
            settings["hooks"]["Stop"][0]["hooks"][0]["command"],
            "seite check --hook claude"
        );
        let paths: Vec<_> = files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&".codex/hooks.json"));
        assert!(paths.contains(&".cursor/hooks.json"));
        assert!(paths.contains(&OPENCODE_PLUGIN_PATH));
    }

    #[test]
    fn find_site_root_walks_up() {
        let tmp = tempfile::TempDir::new().unwrap();
        let site = tmp.path().join("site");
        std::fs::create_dir_all(site.join("content/posts")).unwrap();
        std::fs::write(site.join("seite.toml"), "").unwrap();
        let found = find_site_root(&[site.join("content/posts")]).unwrap();
        assert_eq!(found, site);
        assert_ne!(find_site_root(&[tmp.path().to_path_buf()]), Some(site));
    }
}
