use super::common::*;

#[test]
fn test_build_minify_css() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Minify Test", "posts");
    let site_dir = tmp.path().join("site");

    // minify = true is the default for new sites generated by `seite init`
    write_static_css(
        &site_dir,
        "style.css",
        "/* header styles */\nbody {\n    color : red ;\n    background : blue ;\n}\n",
    );

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    let css = fs::read_to_string(site_dir.join("dist/static/style.css")).unwrap();
    assert!(
        !css.contains("/* header"),
        "minified CSS should not contain comments"
    );
    assert!(
        !css.contains("    "),
        "minified CSS should not have indentation"
    );
    assert!(
        css.contains("color:red"),
        "minified CSS should collapse whitespace around colon"
    );
}

#[test]
fn test_build_fingerprint_writes_manifest() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Fingerprint Test", "posts");
    let site_dir = tmp.path().join("site");

    write_static_css(&site_dir, "main.css", "body { color: red; }");
    set_build_option(&site_dir, "fingerprint", "true");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    // Manifest must exist
    let manifest_path = site_dir.join("dist/asset-manifest.json");
    assert!(
        manifest_path.exists(),
        "asset-manifest.json should be generated"
    );
    let manifest = fs::read_to_string(&manifest_path).unwrap();
    assert!(
        manifest.contains("/static/main.css"),
        "manifest should map original path"
    );
    // Fingerprinted file should exist alongside original
    let dist_static = site_dir.join("dist/static");
    let has_fingerprinted = fs::read_dir(&dist_static).unwrap().any(|e| {
        e.ok()
            .and_then(|e| e.file_name().into_string().ok())
            .map(|n| n.starts_with("main.") && n.ends_with(".css") && n != "main.css")
            .unwrap_or(false)
    });
    assert!(
        has_fingerprinted,
        "fingerprinted CSS file should exist in dist/static"
    );
}

#[test]
fn test_build_no_minify_by_default() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "No Minify Test", "posts");
    let site_dir = tmp.path().join("site");

    let original_css = "/* keep this comment */\nbody {\n    color: red;\n}\n";
    write_static_css(&site_dir, "style.css", original_css);
    // Explicitly opt out of minification
    set_build_option(&site_dir, "minify", "false");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    let css = fs::read_to_string(site_dir.join("dist/static/style.css")).unwrap();
    assert!(
        css.contains("/* keep"),
        "CSS should be unmodified when minify is false"
    );
}

#[test]
fn test_build_image_resize_and_webp() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Image Test", "posts");
    let site_dir = tmp.path().join("site");

    write_test_image(&site_dir, "photo.png");
    set_images_config(&site_dir, "[48]");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    // Original should be copied
    assert!(site_dir.join("dist/static/images/photo.png").exists());
    // Resized version should exist
    assert!(
        site_dir.join("dist/static/images/photo-48w.png").exists(),
        "resized PNG at 48w should exist"
    );
    // WebP version should exist
    assert!(
        site_dir.join("dist/static/images/photo-48w.webp").exists(),
        "resized WebP at 48w should exist"
    );
    // Full-size WebP should exist
    assert!(
        site_dir.join("dist/static/images/photo.webp").exists(),
        "full-size WebP should exist"
    );
}

#[test]
fn test_build_image_lazy_loading() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Lazy Test", "posts,pages");
    let site_dir = tmp.path().join("site");

    // Create a page with two image references — first is skipped for LCP, second gets lazy
    let page_content =
        "---\ntitle: Gallery\n---\n\n![First](/static/images/photo.png)\n\n![Second](/static/images/photo.png)\n";
    fs::write(site_dir.join("content/pages/gallery.md"), page_content).unwrap();

    write_test_image(&site_dir, "photo.png");
    set_images_config(&site_dir, "[48]");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    let html = fs::read_to_string(site_dir.join("dist/gallery.html")).unwrap();
    // Second image should get lazy loading (first is skipped for LCP)
    assert!(
        html.contains("loading=\"lazy\""),
        "second img tag should have loading=lazy"
    );
}

#[test]
fn test_build_image_srcset_in_html() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Srcset Test", "posts,pages");
    let site_dir = tmp.path().join("site");

    let page_content = "---\ntitle: Gallery\n---\n\n![A photo](/static/images/photo.png)\n";
    fs::write(site_dir.join("content/pages/gallery.md"), page_content).unwrap();

    write_test_image(&site_dir, "photo.png");
    set_images_config(&site_dir, "[48]");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    let html = fs::read_to_string(site_dir.join("dist/gallery.html")).unwrap();
    assert!(
        html.contains("srcset="),
        "img tags should have srcset attribute"
    );
    assert!(
        html.contains("48w"),
        "srcset should include the 48w variant"
    );
}

#[test]
fn test_build_image_picture_element_webp() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Picture Test", "posts,pages");
    let site_dir = tmp.path().join("site");

    let page_content = "---\ntitle: Gallery\n---\n\n![A photo](/static/images/photo.png)\n";
    fs::write(site_dir.join("content/pages/gallery.md"), page_content).unwrap();

    write_test_image(&site_dir, "photo.png");
    set_images_config(&site_dir, "[48]");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    let html = fs::read_to_string(site_dir.join("dist/gallery.html")).unwrap();
    assert!(
        html.contains("<picture>"),
        "should wrap in <picture> element for WebP"
    );
    assert!(html.contains("image/webp"), "should have WebP source type");
    assert!(
        html.contains("</picture>"),
        "should close <picture> element"
    );
}

#[test]
fn test_build_image_skip_larger_than_original() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Skip Large Test", "posts");
    let site_dir = tmp.path().join("site");

    // Image is 100x100, so widths > 100 should be skipped
    write_test_image(&site_dir, "small.png");
    set_images_config(&site_dir, "[48, 200, 1200]");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    // 48w should exist (smaller than 100)
    assert!(site_dir.join("dist/static/images/small-48w.png").exists());
    // 200w should NOT exist (larger than 100)
    assert!(!site_dir.join("dist/static/images/small-200w.png").exists());
    // 1200w should NOT exist
    assert!(!site_dir.join("dist/static/images/small-1200w.png").exists());
}

#[test]
fn test_build_no_image_processing_without_config() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "No Image Config", "posts");
    let site_dir = tmp.path().join("site");

    // Remove the [images] section so image processing is truly disabled
    let toml_path = site_dir.join("seite.toml");
    let config = fs::read_to_string(&toml_path).unwrap();
    if let Some(pos) = config.find("\n[images]") {
        fs::write(&toml_path, &config[..pos]).unwrap();
    }

    write_test_image(&site_dir, "photo.png");

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    // Original should be copied as-is by static file step
    assert!(site_dir.join("dist/static/images/photo.png").exists());
    // No [images] config means no processing at all — no resizes, no WebP
    assert!(!site_dir.join("dist/static/images/photo-480w.png").exists());
    assert!(!site_dir.join("dist/static/images/photo.webp").exists());
}

#[test]
fn test_build_image_avif_generation() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "AVIF Test", "posts");
    let site_dir = tmp.path().join("site");

    write_test_image(&site_dir, "photo.png");

    // Add AVIF config
    let toml_path = site_dir.join("seite.toml");
    let mut config = fs::read_to_string(&toml_path).unwrap();
    if let Some(pos) = config.find("\n[images]") {
        config.truncate(pos);
    }
    config.push_str(
        "\n[images]\nwidths = [48]\nquality = 80\nlazy_loading = true\nwebp = true\navif = true\navif_quality = 70\n",
    );
    fs::write(&toml_path, config).unwrap();

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    // Resized AVIF should exist
    assert!(
        site_dir.join("dist/static/images/photo-48w.avif").exists(),
        "resized AVIF at 48w should exist"
    );
    // Full-size AVIF should exist
    assert!(
        site_dir.join("dist/static/images/photo.avif").exists(),
        "full-size AVIF should exist"
    );
    // WebP should also exist (both enabled)
    assert!(site_dir.join("dist/static/images/photo-48w.webp").exists());
}

#[test]
fn test_build_image_avif_picture_element() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "AVIF Picture Test", "posts,pages");
    let site_dir = tmp.path().join("site");

    let page_content = "---\ntitle: Gallery\n---\n\n![A photo](/static/images/photo.png)\n";
    fs::write(site_dir.join("content/pages/gallery.md"), page_content).unwrap();

    write_test_image(&site_dir, "photo.png");

    let toml_path = site_dir.join("seite.toml");
    let mut config = fs::read_to_string(&toml_path).unwrap();
    if let Some(pos) = config.find("\n[images]") {
        config.truncate(pos);
    }
    config.push_str(
        "\n[images]\nwidths = [48]\nquality = 80\nlazy_loading = true\nwebp = true\navif = true\navif_quality = 70\n",
    );
    fs::write(&toml_path, config).unwrap();

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    let html = fs::read_to_string(site_dir.join("dist/gallery.html")).unwrap();
    assert!(html.contains("image/avif"), "should have AVIF source type");
    assert!(html.contains("image/webp"), "should have WebP source type");
    // AVIF should appear before WebP in the HTML
    let avif_pos = html.find("image/avif").unwrap();
    let webp_pos = html.find("image/webp").unwrap();
    assert!(
        avif_pos < webp_pos,
        "AVIF source should appear before WebP for browser priority"
    );
}

#[test]
fn test_build_copies_public_files_to_root() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Public Files", "posts");
    let site_dir = tmp.path().join("site");

    // Place files in public/
    fs::write(site_dir.join("public/favicon.ico"), "fake-icon").unwrap();
    fs::create_dir_all(site_dir.join("public/.well-known")).unwrap();
    fs::write(
        site_dir.join("public/.well-known/security.txt"),
        "Contact: security@example.com",
    )
    .unwrap();

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    // Verify files appear at dist/ root, not dist/public/
    assert!(site_dir.join("dist/favicon.ico").exists());
    assert_eq!(
        fs::read_to_string(site_dir.join("dist/favicon.ico")).unwrap(),
        "fake-icon"
    );
    assert!(site_dir.join("dist/.well-known/security.txt").exists());
    assert_eq!(
        fs::read_to_string(site_dir.join("dist/.well-known/security.txt")).unwrap(),
        "Contact: security@example.com"
    );
}

#[test]
fn test_build_generated_files_overwrite_public() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "site", "Public Override", "posts");
    let site_dir = tmp.path().join("site");

    // Place a robots.txt in public/
    fs::write(
        site_dir.join("public/robots.txt"),
        "User-agent: none\nDisallow: /",
    )
    .unwrap();

    page_cmd()
        .arg("build")
        .current_dir(&site_dir)
        .assert()
        .success();

    // Generated robots.txt should win (contains Sitemap: line)
    let robots = fs::read_to_string(site_dir.join("dist/robots.txt")).unwrap();
    assert!(
        robots.contains("Sitemap:"),
        "Generated robots.txt should overwrite public/ version"
    );
}

#[test]
fn test_build_with_public_dir() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "pubsite", "Public Test", "posts");
    let site_dir = tmp.path().join("pubsite");

    // Place a file in public/
    fs::create_dir_all(site_dir.join("public")).unwrap();
    fs::write(site_dir.join("public/favicon.ico"), "icon").unwrap();

    page_cmd()
        .args(["build"])
        .current_dir(&site_dir)
        .assert()
        .success();

    // Public files should be copied to dist/
    assert!(site_dir.join("dist/favicon.ico").exists());
}

// --- build with images config ---

#[test]
fn test_build_with_images_config() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "imgcfg", "Images Config", "posts");
    let site_dir = tmp.path().join("imgcfg");

    // Replace the default images config with custom widths
    let config_path = site_dir.join("seite.toml");
    let config = fs::read_to_string(&config_path).unwrap();
    // init_site already creates an [images] section, so replace it
    let config = config.replace(
        "[images]\nwidths = [480, 800, 1200]\nquality = 80\nlazy_loading = true\nwebp = true",
        "[images]\nwidths = [480, 800]\nquality = 85\nlazy_loading = true\nwebp = true",
    );
    fs::write(&config_path, config).unwrap();

    page_cmd()
        .args(["build"])
        .current_dir(&site_dir)
        .assert()
        .success();
}

// --- build with minify and fingerprint ---

#[test]
fn test_build_with_minify_and_fingerprint() {
    let tmp = TempDir::new().unwrap();
    init_site(&tmp, "minify", "Minify Test", "posts");
    let site_dir = tmp.path().join("minify");

    // minify = true is already the default; just add fingerprint
    set_build_option(&site_dir, "fingerprint", "true");

    // Create a static CSS file
    fs::create_dir_all(site_dir.join("static")).unwrap();
    fs::write(
        site_dir.join("static/style.css"),
        "/* comment */ body { margin: 0; }",
    )
    .unwrap();

    page_cmd()
        .args(["build"])
        .current_dir(&site_dir)
        .assert()
        .success();

    // Check that asset-manifest.json exists (fingerprinting)
    assert!(site_dir.join("dist/asset-manifest.json").exists());
}
